# Generated by Django 5.1 on 2024-08-21 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='value_gte_0')],
            },
        ),
    ]
